version: '3.3'

services:
    user:
      build:
        context: ./
        dockerfile: user/Dockerfile
      image: user
      container_name: user
      restart: unless-stopped
      ports:
       - "8080:8080"
      links: 
        - vehicle
      depends_on:
        - postgres

    vehicle:
      build:
        context: ./
        dockerfile: vehicle/Dockerfile
      image: vehicle
      container_name: vehicle
      restart: unless-stopped
      ports:
       - "8085:8085"
      depends_on:
        - postgres

    policy:
      build:
        context: ./
        dockerfile: policy/Dockerfile
      image: policy
      container_name: policy
      restart: unless-stopped
      ports:
       - "8086:8086"
      depends_on:
        - postgres

    postgres:
      image: postgres:latest
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=onsite
      volumes:
        - ./schema:/docker-entrypoint-initdb.d/
      ports:
        - 5432:5432
